### ISSUE TITLE
Calc doesn't work after minification

### ISSUE THREAD

**Issue by ElGovanni** [yui/yuicompressor#268]
For example: 
if I have class like this
```
.xd {
 font-size: calc(0.8vh + 0.8vw); 
} 
```
after minification turns into: 
`.xd {font-size: calc(0.8vh+0.8vw);} `

As we see yui remove space between values of calc and plus, so browser cannot calculate new size.
Please fix it.
![anime-7](https://cloud.githubusercontent.com/assets/14053391/22693600/34f3afae-ed44-11e6-98ab-c361445fcb66.png)

**Comment by nineoclick** [comment]
I beg to copy paste here the solution I mentioned [here](https://github.com/yui/yuicompressor/issues/59).

**Encountered this bug and found a solution that works great for me.**
My setup is: PhpStorm with LESS and YUI Compressor CSS watchers. So usually I work with a less file, that outputs to css file and then YUI Compressor as watcher minifies the css.

**My solution**

Less File:
```
.@{css_root}-mainContentRight {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  display: inline-block;
  height: 200px;
  width: calc(~"100% -  " @mainContentDivDefaultMargin*4 + @mainContentLeftWidth);
  background: #bacd63;
  padding: @mainContentDivDefaultPadding;
  margin: @mainContentDivDefaultMargin;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}
```
Now: on width rule, I put **two** spaces between the **minus** sign AND **one** space after closing the unescaped string. **See below**:
`width: calc(~"100% -`**SpaceSpace**`"`**Space**`@mainContentDivDefaultMargin*4 + @mainContentLeftWidth);`

CSS not compressed that results from LESS

```
.jimlibmus-mainContentRight {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  display: inline-block;
  height: 200px;
  width: calc(100% -   220px);
  background: #bacd63;
  padding: 5px;
  margin: 5px;
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}
```

`width: calc(100% -`**SpaceSpaceSpace**`220px);`

Phpstorm watcher see changes in css file and then starts YUI. The result:

`.jimlibmus-mainContentRight{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;display:inline-block;height:200px;width:calc(100% - 220px);background:#bacd63;padding:5px;margin:5px;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px}`

Now YUI compresses it right.

`width:calc(100% -`**Space**`220px);`

It's simple to become familiar with this ***multiple-space*** practice, and helps me a lot not to banging my head on the desk.

Hope this helps.

**Comment by pichardo** [comment]
Simple solutions should be 
    width: calc(100% - 8px * -1); 
try it, for me this solution work on Adobe AEM using YUI Compresses. Believe me,  just try and then let me know

**Comment by Maggie199** [comment]
Not sure if this is the right place to put it, but looks like the calc() in @keyframes is still not working.

**Comment by ivanhub** [comment]
This: font-size: calc(0.8vh - -0.8vw); 
only works for me

**Comment by PeterLenahan** [comment]
Before compression
	.file-item {
		width: calc(100vw - 40px);
		height: calc(((100vw - 40px) * .73) + 40px);
	}
After compression, the spaces are missing.

.file-item{width:calc(100vw - 40px);height:calc(((100vw - 40px) * **.73)+40px)}**

**Comment by KingFishTheKing** [comment]
I have a found a solution which worked for me. It isn't as much of a solution as it is a workaround.
It used base64 encoding on a @import rule, which is totally fine for the compressor.
I'll try to explain as best as I can.

1). First thing you want to do is create a separate file with your css-rules which give you trouble in it
<img width="281" alt="screen shot 2018-05-22 at 17 58 09" src="https://user-images.githubusercontent.com/26142458/40374650-c5db4844-5de9-11e8-9ce7-d561bdfb2e59.png">
_Notice: you have to declare the charset on top else it might give you trouble in certain browsers._

2.) Next thing you will have to do is find a base64 encoder somewhere (I personally use [Base64Anywhere](https://itunes.apple.com/us/app/base64anywhere/id640841706?mt=12) but it's a mac only application as far as I know) and paste the plain text into your encoder, do not encode the whole file because it will not work.
This will give you a bunch (depending on how many rules you have this can be quite a lot) of seemingly random characters thrown together.
 <img width="716" alt="screen shot 2018-05-22 at 18 02 43" src="https://user-images.githubusercontent.com/26142458/40374982-9fa91696-5dea-11e8-8ed4-d477fc548f56.png">

3.) Open the css file where you'd normally had written your rules
4.) At the very top (!) write and @import rule with a url parameter.
5.) Insert this piece of code between the quote marks 

> data:text/css;base64,

6.) Paste your base64 encoded gibberish behind the comma (still in between the quote marks)
<img width="965" alt="screen shot 2018-05-22 at 18 10 40" src="https://user-images.githubusercontent.com/26142458/40375276-79040e1e-5deb-11e8-8943-e92c659f8347.png">
<img width="1433" alt="screen shot 2018-05-22 at 18 12 03" src="https://user-images.githubusercontent.com/26142458/40375727-b2a43eae-5dec-11e8-84a3-359b8d23b1f8.png">


And there you go, the css rule gets applied and the source is the string of gibberish that is our base64 encoded url.

So why does this work, well the compressor only looks for comments, white spaces and other stuff is can rip out without breaking everything. It looks at the @import line and is like 'meh no whitespace better move on' then when your browser reads the line is says it has to go and collect an additional resource defined by the url() parameter so it tries to but then the first statement says it's not actually a url but the data itself, the second part defines what type it is (in our case 'text/css') so the browser now knows it's going to have to try and read css-rules, the third paramater then says that the data following is base64 encoded so now the browser now it has to 
1. decode the string (with our spaces in it) 2. read it as css 3. include it in the current document.

**!!
Important
- Only encode the rules themselfs, encode the file and it won't work
- Charset utf-8
- @import rules have to be written at the very top of the stylesheet or they won't work
!!**

**Comment by Renrhaf** [comment]
Confirming issue when using YUI Compressor in the Advagg CSS Minifier Drupal module.
For reference, see : https://www.drupal.org/project/drupal/issues/2820365#comment-12922559

**Comment by kengruven** [comment]
Was this fixed?  I see it was "closed" but I see no recent commits.

**Comment by Chris2011** [comment]
If u follow the repo and other tickets, you could see that this repo is not maintained anymore. So i would suggest to use another compressir

**Comment by kengruven** [comment]
Thanks for the info -- though I really don't know how I would have discovered that.  No other issues here were closed, and the documentation and webpage don't mention anything about that.

**Comment by Chris2011** [comment]
Some others were closed with some comments.

**Comment by Chris2011** [comment]
But yeah, an info at the readme page would be helpful.
