### ISSUE TITLE
No ability to suppress important comments in minified/obfuscated output

### ISSUE THREAD

**Issue by jvd-nl** [yui/yuicompressor#61]
For security reasons, there might be scenario's in which you would like to remove all comments of a file, including the so called important comments.

Since a couple of versions back (somewhere in 2009), the default behavior was changed to not include these important comments when removing all comments. 

It would be good to have an option to remove these comments anyway.
E.g. --remove-all-comments

E.g. 
/_! This comment will not be removed, but it includes a version number that attackers might be interested in on production servers */
// this comment will be removed
/_ this one too */

**Comment by josenobile** [comment]
One reason:
I'm loosing points in Google PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/) because the CSS minifier leave the comments, when I download the optimized files from Google I get the css minified with no one comment. 

Google PageSpeed is very important, it is used for:
Google SEO
Google Mobile test (if you are under the points required to pass the mobile friendly, to are losing a lot of mobile traffic.
